### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by mchalupa** [yaqwsx/SymDIVINE#1]
CMake Error at CMakeLists.txt:54 (add_executable):
  Cannot find source file:

```
libs/docopt/docopt.cpp
```

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

There is no such file in SymDIVINE

**Comment by yaqwsx** [comment]
`git submodule update --init --recursive`
